### ISSUE TITLE
Installation fails with Python 3.11

### ISSUE THREAD

**Issue by dkp** [yeatmanlab/pyAFQ#1010]
Ubuntu 22: conda install.

This works:
```bash
conda create -n pyafq python=3.9
conda activate pyafq
pip install pyAFQ
```

This does not work:
```bash
conda create -n pyafq311 python=3.11
conda activate pyafq311
pip install pyAFQ
```
The following error is reported for the python 3.11 environment:
```bash
Collecting pyAFQ
  Using cached pyAFQ-1.0.1-py3-none-any.whl (282 kB)
Collecting scikit-image>=0.14.2 (from pyAFQ)
  Obtaining dependency information for scikit-image>=0.14.2 from https://files.pythonhosted.org/packages/22/c3/c5f3c351d6337a18d07c3fb04475626c106cd3dc3d59b85ec50d07656db0/scikit_image-0.21.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata
  Using cached scikit_image-0.21.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (14 kB)
Collecting dipy<1.6.0,>=1.5.0 (from pyAFQ)
  Using cached dipy-1.5.0.tar.gz (11.8 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/var/tmp/pip-install-bca7hbbm/dipy_d7246572e2104892a146e1fc6e97de9d/setup.py", line 34, in <module>
          from cythexts import cyproc_exts, get_pyx_sdist
        File "/var/tmp/pip-install-bca7hbbm/dipy_d7246572e2104892a146e1fc6e97de9d/cythexts.py", line 7, in <module>
          from packaging.version import Version
      ModuleNotFoundError: No module named 'packaging'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by 36000** [comment]
Does it work if you do:
```
conda create -n pyafq311 python=3.11
conda activate pyafq311
pip install packaging
pip install pyAFQ
```

**Comment by dkp** [comment]
Interesting, thank you!  Unfortunately, this still fails:

```bash
[dema:dwi () 2069] $ conda create -n pyafq311 python=3.11
Collecting package metadata (current_repodata.json): done
Solving environment: done


==> WARNING: A newer version of conda exists. <==
  current version: 23.3.1
  latest version: 23.7.3

Please update conda by running

    $ conda update -n base -c defaults conda

Or to minimize the number of packages updated during conda update use

     conda install conda=23.7.3



## Package Plan ##

  environment location: /home/dpat/miniconda3/envs/pyafq311

  added / updated specs:
    - python=3.11


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    _libgcc_mutex-0.1          |      conda_forge           3 KB  conda-forge
    _openmp_mutex-4.5          |            2_gnu          23 KB  conda-forge
    libexpat-2.5.0             |       hcb278e6_1          76 KB  conda-forge
    python-3.11.5              |hab00c5b_0_cpython        29.4 MB  conda-forge
    ------------------------------------------------------------
                                           Total:        29.5 MB

The following NEW packages will be INSTALLED:

  _libgcc_mutex      conda-forge/linux-64::_libgcc_mutex-0.1-conda_forge
  _openmp_mutex      conda-forge/linux-64::_openmp_mutex-4.5-2_gnu
  bzip2              conda-forge/linux-64::bzip2-1.0.8-h7f98852_4
  ca-certificates    conda-forge/linux-64::ca-certificates-2023.7.22-hbcca054_0
  ld_impl_linux-64   conda-forge/linux-64::ld_impl_linux-64-2.40-h41732ed_0
  libexpat           conda-forge/linux-64::libexpat-2.5.0-hcb278e6_1
  libffi             conda-forge/linux-64::libffi-3.4.2-h7f98852_5
  libgcc-ng          conda-forge/linux-64::libgcc-ng-13.1.0-he5830b7_0
  libgomp            conda-forge/linux-64::libgomp-13.1.0-he5830b7_0
  libnsl             conda-forge/linux-64::libnsl-2.0.0-h7f98852_0
  libsqlite          conda-forge/linux-64::libsqlite-3.43.0-h2797004_0
  libuuid            conda-forge/linux-64::libuuid-2.38.1-h0b41bf4_0
  libzlib            conda-forge/linux-64::libzlib-1.2.13-hd590300_5
  ncurses            conda-forge/linux-64::ncurses-6.4-hcb278e6_0
  openssl            conda-forge/linux-64::openssl-3.1.2-hd590300_0
  pip                conda-forge/noarch::pip-23.2.1-pyhd8ed1ab_0
  python             conda-forge/linux-64::python-3.11.5-hab00c5b_0_cpython
  readline           conda-forge/linux-64::readline-8.2-h8228510_1
  setuptools         conda-forge/noarch::setuptools-68.1.2-pyhd8ed1ab_0
  tk                 conda-forge/linux-64::tk-8.6.12-h27826a3_0
  tzdata             conda-forge/noarch::tzdata-2023c-h71feb2d_0
  wheel              conda-forge/noarch::wheel-0.41.2-pyhd8ed1ab_0
  xz                 conda-forge/linux-64::xz-5.2.6-h166bdaf_0


Proceed ([y]/n)? y


Downloading and Extracting Packages

Preparing transaction: done
Verifying transaction: done
Executing transaction: done
#
# To activate this environment, use
#
#     $ conda activate pyafq311
#
# To deactivate an active environment, use
#
#     $ conda deactivate

[dema:dwi () 2070] $ conda activate pyafq311
(pyafq311) [dema:dwi () 2071] $ pip install packaging
Collecting packaging
  Using cached packaging-23.1-py3-none-any.whl (48 kB)
Installing collected packages: packaging
Successfully installed packaging-23.1
(pyafq311) [dema:dwi () 2072] $ pip install pyAFQ
Collecting pyAFQ
  Using cached pyAFQ-1.0.1-py3-none-any.whl (282 kB)
Collecting scikit-image>=0.14.2 (from pyAFQ)
  Obtaining dependency information for scikit-image>=0.14.2 from https://files.pythonhosted.org/packages/22/c3/c5f3c351d6337a18d07c3fb04475626c106cd3dc3d59b85ec50d07656db0/scikit_image-0.21.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata
  Using cached scikit_image-0.21.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (14 kB)
Collecting dipy<1.6.0,>=1.5.0 (from pyAFQ)
  Using cached dipy-1.5.0.tar.gz (11.8 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [15 lines of output]
      /home/dpat/miniconda3/envs/pyafq311/lib/python3.11/site-packages/setuptools/config/setupcfg.py:293: _DeprecatedConfig: Deprecated config in `setup.cfg`
      !!

              ********************************************************************************
              The license_file parameter is deprecated, use license_files instead.

              By 2023-Oct-30, you need to update your project and remove deprecated calls
              or your builds will no longer be supported.

              See https://setuptools.pypa.io/en/latest/userguide/declarative_config.html for details.
              ********************************************************************************

      !!
        parsed = self.parsers.get(option_name, lambda x: x)(value)
      error in dipy setup command: 'extras_require' must be a dictionary whose values are strings or lists of strings containing valid project/version requirement specifiers.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by 36000** [comment]
Ah I see, yes, this is fixed on master. You can try installing the development version ( https://yeatmanlab.github.io/pyAFQ/installation_guide.html ), or you can just install dipy first:

pip install dipy==1.7.0
pip install pyAFQ

@arokem  we should consider releasing a new version of pyAFQ soon
