### ISSUE TITLE
NameError: name 'TrxFile' is not defined (for RecoBundles and plot AFQ examples)

### ISSUE THREAD

**Issue by chiuhoward** [yeatmanlab/pyAFQ#1023]
Same errors when running RecoBundles and plot AFQ examples in the pimms and AFQ package scripts...

```
INFO:AFQ:Saving /Users/howardchiu/AFQ_data/stanford_hardi/derivatives/afq/sub-01/ses-01/sub-01_ses-01_dwi_space-RASMM_model-probCSD_algo-reco80_desc-profiles_dwi.csv
Traceback (most recent call last):
  File "/Users/howardchiu/AFQ_data/plot_afq_reco80.py", line 59, in <module>
    bundle_html = myafq.export("all_bundles_figure")
  File "/Users/howardchiu/miniconda3/envs/pyAFQ1.1/lib/python3.9/site-packages/AFQ/api/group.py", line 434, in export
    results[subject][session] = wf_dict[attr_name]
  File "/Users/howardchiu/miniconda3/envs/pyAFQ1.1/lib/python3.9/site-packages/pimms/calculation.py", line 470, in __getitem__
    self._run_node(self.plan.efferents[k])
  File "/Users/howardchiu/miniconda3/envs/pyAFQ1.1/lib/python3.9/site-packages/pimms/calculation.py", line 534, in _run_node
    if not found: res = node(self)
  File "/Users/howardchiu/miniconda3/envs/pyAFQ1.1/lib/python3.9/site-packages/pimms/calculation.py", line 91, in __call__
    result = self.function(*args)
  File "/Users/howardchiu/miniconda3/envs/pyAFQ1.1/lib/python3.9/site-packages/AFQ/tasks/viz.py", line 81, in viz_bundles
    profiles_file = segmentation_imap["profiles"]
  File "/Users/howardchiu/miniconda3/envs/pyAFQ1.1/lib/python3.9/site-packages/pimms/calculation.py", line 470, in __getitem__
    self._run_node(self.plan.efferents[k])
  File "/Users/howardchiu/miniconda3/envs/pyAFQ1.1/lib/python3.9/site-packages/pimms/calculation.py", line 534, in _run_node
    if not found: res = node(self)
  File "/Users/howardchiu/miniconda3/envs/pyAFQ1.1/lib/python3.9/site-packages/pimms/calculation.py", line 91, in __call__
    result = self.function(*args)
  File "<string>", line 2, in wrapper_has_args_func
  File "/Users/howardchiu/miniconda3/envs/pyAFQ1.1/lib/python3.9/site-packages/AFQ/tasks/decorators.py", line 157, in wrapper_as_file
    elif isinstance(gen, TrxFile):
NameError: name 'TrxFile' is not defined
```

**Comment by arokem** [comment]
Hopefully addressed by https://github.com/yeatmanlab/pyAFQ/pull/1020
