### ISSUE TITLE
ValueError: No file found with these parameters: suffix, session, subject, filters, near path

### ISSUE THREAD

**Issue by chiuhoward** [yeatmanlab/pyAFQ#1024]
For the subject space ROI example - I don’t understand this log at all, but someone else might...

```
INFO:AFQ:Saving /Users/howardchiu/AFQ_data/stanford_hardi/derivatives/afq/sub-01/ses-01/sub-01_ses-01_dwi_desc-maskedb0_dwi.nii.gz
Traceback (most recent call last):
  File "/Users/howardchiu/AFQ_data/use_subject_space_rois_from_freesurfer.py", line 141, in <module>
    bundle_html = myafq.export("indiv_bundles_figures")
  File "/Users/howardchiu/miniconda3/envs/pyAFQ1.1/lib/python3.9/site-packages/AFQ/api/group.py", line 434, in export
    results[subject][session] = wf_dict[attr_name]
  File "/Users/howardchiu/miniconda3/envs/pyAFQ1.1/lib/python3.9/site-packages/pimms/calculation.py", line 470, in __getitem__
    self._run_node(self.plan.efferents[k])
  File "/Users/howardchiu/miniconda3/envs/pyAFQ1.1/lib/python3.9/site-packages/pimms/calculation.py", line 534, in _run_node
    if not found: res = node(self)
  File "/Users/howardchiu/miniconda3/envs/pyAFQ1.1/lib/python3.9/site-packages/pimms/calculation.py", line 91, in __call__
    result = self.function(*args)
  File "/Users/howardchiu/miniconda3/envs/pyAFQ1.1/lib/python3.9/site-packages/AFQ/tasks/viz.py", line 187, in viz_indivBundle
    profiles = pd.read_csv(segmentation_imap["profiles"])
  File "/Users/howardchiu/miniconda3/envs/pyAFQ1.1/lib/python3.9/site-packages/pimms/calculation.py", line 470, in __getitem__
    self._run_node(self.plan.efferents[k])
  File "/Users/howardchiu/miniconda3/envs/pyAFQ1.1/lib/python3.9/site-packages/pimms/calculation.py", line 534, in _run_node
    if not found: res = node(self)
  File "/Users/howardchiu/miniconda3/envs/pyAFQ1.1/lib/python3.9/site-packages/pimms/calculation.py", line 90, in __call__
    args.append(opts[name])
  File "/Users/howardchiu/miniconda3/envs/pyAFQ1.1/lib/python3.9/site-packages/pimms/util.py", line 889, in __getitem__
    return self._examine_val(k, ps.PMap.__getitem__(self, k))
  File "/Users/howardchiu/miniconda3/envs/pyAFQ1.1/lib/python3.9/site-packages/pimms/util.py", line 885, in _examine_val
    val = val()
  File "/Users/howardchiu/miniconda3/envs/pyAFQ1.1/lib/python3.9/site-packages/pimms/util.py", line 1164, in <lambda>
    def curry_choice(k, args): return lambda:choose_fn(k, args)
  File "/Users/howardchiu/miniconda3/envs/pyAFQ1.1/lib/python3.9/site-packages/pimms/util.py", line 1133, in _choose_last
    return vs[-1][k]
  File "/Users/howardchiu/miniconda3/envs/pyAFQ1.1/lib/python3.9/site-packages/pimms/calculation.py", line 470, in __getitem__
    self._run_node(self.plan.efferents[k])
  File "/Users/howardchiu/miniconda3/envs/pyAFQ1.1/lib/python3.9/site-packages/pimms/calculation.py", line 534, in _run_node
    if not found: res = node(self)
  File "/Users/howardchiu/miniconda3/envs/pyAFQ1.1/lib/python3.9/site-packages/pimms/calculation.py", line 91, in __call__
    result = self.function(*args)
  File "<string>", line 2, in wrapper_has_args_func
  File "/Users/howardchiu/miniconda3/envs/pyAFQ1.1/lib/python3.9/site-packages/AFQ/tasks/decorators.py", line 147, in wrapper_as_file
    gen, meta = func(*args[:og_arg_count], **kwargs)
  File "/Users/howardchiu/miniconda3/envs/pyAFQ1.1/lib/python3.9/site-packages/AFQ/tasks/segmentation.py", line 55, in segment
    streamlines = tractography_imap["streamlines"]
  File "/Users/howardchiu/miniconda3/envs/pyAFQ1.1/lib/python3.9/site-packages/pimms/calculation.py", line 470, in __getitem__
    self._run_node(self.plan.efferents[k])
  File "/Users/howardchiu/miniconda3/envs/pyAFQ1.1/lib/python3.9/site-packages/pimms/calculation.py", line 534, in _run_node
    if not found: res = node(self)
  File "/Users/howardchiu/miniconda3/envs/pyAFQ1.1/lib/python3.9/site-packages/pimms/calculation.py", line 90, in __call__
    args.append(opts[name])
  File "/Users/howardchiu/miniconda3/envs/pyAFQ1.1/lib/python3.9/site-packages/pimms/util.py", line 889, in __getitem__
    return self._examine_val(k, ps.PMap.__getitem__(self, k))
  File "/Users/howardchiu/miniconda3/envs/pyAFQ1.1/lib/python3.9/site-packages/pimms/util.py", line 885, in _examine_val
    val = val()
  File "/Users/howardchiu/miniconda3/envs/pyAFQ1.1/lib/python3.9/site-packages/pimms/util.py", line 1164, in <lambda>
    def curry_choice(k, args): return lambda:choose_fn(k, args)
  File "/Users/howardchiu/miniconda3/envs/pyAFQ1.1/lib/python3.9/site-packages/pimms/util.py", line 1133, in _choose_last
    return vs[-1][k]
  File "/Users/howardchiu/miniconda3/envs/pyAFQ1.1/lib/python3.9/site-packages/pimms/calculation.py", line 470, in __getitem__
    self._run_node(self.plan.efferents[k])
  File "/Users/howardchiu/miniconda3/envs/pyAFQ1.1/lib/python3.9/site-packages/pimms/calculation.py", line 534, in _run_node
    if not found: res = node(self)
  File "/Users/howardchiu/miniconda3/envs/pyAFQ1.1/lib/python3.9/site-packages/pimms/calculation.py", line 91, in __call__
    result = self.function(*args)
  File "<string>", line 2, in wrapper_has_args_func
  File "/Users/howardchiu/miniconda3/envs/pyAFQ1.1/lib/python3.9/site-packages/AFQ/tasks/decorators.py", line 147, in wrapper_as_file
    gen, meta = func(*args[:og_arg_count], **kwargs)
  File "/Users/howardchiu/miniconda3/envs/pyAFQ1.1/lib/python3.9/site-packages/AFQ/definitions/image.py", line 336, in image_getter
    return _image_getter_helper(
  File "/Users/howardchiu/miniconda3/envs/pyAFQ1.1/lib/python3.9/site-packages/AFQ/definitions/image.py", line 280, in _image_getter_helper
    bundle_entry = bundle_dict.transform_rois(
  File "/Users/howardchiu/miniconda3/envs/pyAFQ1.1/lib/python3.9/site-packages/AFQ/api/bundle_dict.py", line 591, in transform_rois
    transformed_rois = self.apply_to_rois(
  File "/Users/howardchiu/miniconda3/envs/pyAFQ1.1/lib/python3.9/site-packages/AFQ/api/bundle_dict.py", line 493, in apply_to_rois
    return_vals[roi_type] = func(
  File "/Users/howardchiu/miniconda3/envs/pyAFQ1.1/lib/python3.9/site-packages/AFQ/api/bundle_dict.py", line 366, in _cond_load
    roi_or_sl = find_file(
  File "/Users/howardchiu/miniconda3/envs/pyAFQ1.1/lib/python3.9/site-packages/AFQ/definitions/utils.py", line 107, in find_file
    raise ValueError((
ValueError: No file found with these parameters:
suffix: anat,
session (searched with and without): 01,
subject: 01,
filters: {'scope': 'freesurfer', 'suffix': 'anat', 'desc': 'LV1', 'extension': '.nii.gz'},
near path: /Users/howardchiu/AFQ_data/stanford_hardi/derivatives/afq/sub-01/ses-01/sub-01_ses-01_dwi_desc-b0_dwi.nii.gz,
```

**Comment by 36000** [comment]
Does this fix it: #1031
