### ISSUE TITLE
Edge clipping raises error

### ISSUE THREAD

**Issue by arokem** [yeatmanlab/pyAFQ#1047]
I am trying to run the [plot_afq_api.py example](https://github.com/yeatmanlab/pyAFQ/blob/master/examples/tutorial_examples/plot_afq_api.py), changing only the following: 

```
myafq = GroupAFQ(
    bids_path=op.join(afd.afq_home, 'stanford_hardi'),
    preproc_pipeline='vistasoft',
    tracking_params=tracking_params,
    segmentation_params={"clip_edges": True},
    viz_backend_spec='plotly_no_gif')
```

I believe that's the way to create bundles that are clipped between the inclusion ROIs. This raises (long output pasted below...): 

```
(afq) ➜  tutorial_examples git:(master) ✗ python plot_afq_api.py 
INFO:AFQ:fetching Stanford HARDI data
INFO:dipy.data.fetcher:Dataset is already in place. If you want to fetch it again please first remove the folder /Users/arokem/.dipy/stanford_hardi 
INFO:AFQ:Dataset is already in place. If you want to fetch it again please first remove the folder /Users/arokem/AFQ_data/stanford_hardi/derivatives
/Users/arokem/miniconda3/envs/afq/lib/python3.10/site-packages/bids/layout/validation.py:122: UserWarning: The PipelineDescription field was superseded by GeneratedBy in BIDS 1.4.0. You can use ``pybids upgrade`` to update your derivative dataset.
  warnings.warn("The PipelineDescription field was superseded "
INFO:AFQ:Saving /Users/arokem/AFQ_data/stanford_hardi/derivatives/afq/sub-01/ses-01/sub-01_ses-01_desc-b0_dwi.nii.gz
WARNING:AFQ:It is reccomended that you provide a brain mask. It is provided with the brain_mask_definition argument. Otherwise, the default brain mask is calculated by using OTSU on the median-filtered B0 image. This can be unreliable. 
INFO:AFQ:Saving /Users/arokem/AFQ_data/stanford_hardi/derivatives/afq/sub-01/ses-01/sub-01_ses-01_desc-brain_mask.nii.gz
INFO:AFQ:Saving /Users/arokem/AFQ_data/stanford_hardi/derivatives/afq/sub-01/ses-01/sub-01_ses-01_odfmodel-DTI_desc-diffmodel_dwi.nii.gz
INFO:AFQ:Saving /Users/arokem/AFQ_data/stanford_hardi/derivatives/afq/sub-01/ses-01/sub-01_ses-01_odfmodel-DTI_desc-FA_dwi.nii.gz
100%|███████████████████████████████| 179864/179864.0 [00:27<00:00, 6494.08it/s]
INFO:AFQ:Saving /Users/arokem/AFQ_data/stanford_hardi/derivatives/afq/sub-01/ses-01/sub-01_ses-01_odfmodel-CSD_desc-diffmodel_dwi.nii.gz
INFO:AFQ:Saving /Users/arokem/AFQ_data/stanford_hardi/derivatives/afq/sub-01/ses-01/sub-01_ses-01_odfmodel-CSD_desc-APM_dwi.nii.gz
Optimizing level 2 [max iter: 10000]
Optimizing level 1 [max iter: 1000]
Optimizing level 0 [max iter: 100]
Optimizing level 2 [max iter: 10000]
Optimizing level 1 [max iter: 1000]
Optimizing level 0 [max iter: 100]
Optimizing level 2 [max iter: 10000]
Optimizing level 1 [max iter: 1000]
Optimizing level 0 [max iter: 100]
INFO:AFQ:Saving /Users/arokem/AFQ_data/stanford_hardi/derivatives/afq/sub-01/ses-01/sub-01_ses-01_desc-prealign_from-DWI_to-MNI_xform.npy
INFO:dipy.align.imwarp:Creating scale space from the moving image. Levels: 3. Sigma factor: 0.200000.
INFO:dipy.align.imwarp:Creating scale space from the static image. Levels: 3. Sigma factor: 0.200000.
INFO:dipy.align.imwarp:Optimizing level 2
INFO:dipy.align.imwarp:Optimizing level 1
INFO:dipy.align.imwarp:Optimizing level 0
INFO:AFQ:Saving /Users/arokem/AFQ_data/stanford_hardi/derivatives/afq/sub-01/ses-01/sub-01_ses-01_desc-mapping_from-DWI_to-MNI_xform.nii.gz
INFO:AFQ:Saving /Users/arokem/AFQ_data/stanford_hardi/derivatives/afq/sub-01/ses-01/sub-01_ses-01_odfmodel-DTI_desc-MD_dwi.nii.gz
INFO:AFQ:Saving /Users/arokem/AFQ_data/stanford_hardi/derivatives/afq/sub-01/ses-01/sub-01_ses-01_coordsys-RASMM_trkmethod-probCSD_desc-seed_mask.nii.gz
INFO:AFQ:Saving /Users/arokem/AFQ_data/stanford_hardi/derivatives/afq/sub-01/ses-01/sub-01_ses-01_coordsys-RASMM_trkmethod-probCSD_desc-stop_mask.nii.gz
INFO:AFQ:Loading Image...
INFO:AFQ:Generating Seeds...
INFO:AFQ:Getting Directions...
INFO:AFQ:Tracking...
 49%|█████████████████▋                  | 12265/25000 [00:36<00:44, 286.40it/s]INFO:root:Temporary folder for memmaps: /var/folders/px/t5ym05pn5k16nz97mzcpqqkr0000gn/T/trx_vr6yuew1
 98%|███████████████████████████████████▍| 24620/25000 [01:13<00:01, 362.17it/s]INFO:root:Temporary folder for memmaps: /var/folders/px/t5ym05pn5k16nz97mzcpqqkr0000gn/T/trx_kjjqb9yn
INFO:root:Temporary folder for memmaps: /var/folders/px/t5ym05pn5k16nz97mzcpqqkr0000gn/T/trx_kfgrr_1y
INFO:root:Resizing streamlines from size 10000 to 20000
INFO:root:Resizing vertices from size 2116221 to 4244092
100%|████████████████████████████████████| 25000/25000 [01:15<00:00, 332.05it/s]
INFO:root:Temporary folder for memmaps: /var/folders/px/t5ym05pn5k16nz97mzcpqqkr0000gn/T/trx_8nqz9r3o
INFO:root:Temporary folder for memmaps: /var/folders/px/t5ym05pn5k16nz97mzcpqqkr0000gn/T/trx_m_bhb9md
INFO:root:Resizing streamlines from size 20000 to 20302
INFO:root:Resizing vertices from size 4244092 to 4306821
INFO:AFQ:Saving /Users/arokem/AFQ_data/stanford_hardi/derivatives/afq/sub-01/ses-01/sub-01_ses-01_coordsys-RASMM_trkmethod-probCSD_tractography.trx
INFO:AFQ:Preparing Segmentation Parameters
INFO:AFQ:Preprocessing Streamlines
INFO:AFQ:Assigning Streamlines to Bundles
INFO:AFQ:Finding Streamlines for ATR_L
INFO:AFQ:Filtering by Prob. Map
INFO:AFQ:After filtering by Prob. Map (time: 0.013858795166015625s), 12796 streamlines remain.
INFO:AFQ:Filtering by Cross Mid.
INFO:AFQ:After filtering by Cross Mid. (time: 0.00034999847412109375s), 6654 streamlines remain.
INFO:AFQ:Filtering by startpoint
INFO:AFQ:After filtering by startpoint (time: 0.5499467849731445s), 2391 streamlines remain.
INFO:AFQ:Filtering by endpoint
INFO:AFQ:After filtering by endpoint (time: 0.016148090362548828s), 213 streamlines remain.
INFO:AFQ:Filtering by include
INFO:AFQ:After filtering by include (time: 0.020704984664916992s), 86 streamlines remain.
INFO:AFQ:Filtering by exclude
INFO:AFQ:After filtering by exclude (time: 8.082389831542969e-05s), 86 streamlines remain.
INFO:AFQ:Filtering by Mahalanobis
INFO:AFQ:After filtering by Mahalanobis (time: 0.02162909507751465s), 33 streamlines remain.
INFO:AFQ:Finding Streamlines for ATR_R
INFO:AFQ:Filtering by Prob. Map
INFO:AFQ:After filtering by Prob. Map (time: 0.015490055084228516s), 12923 streamlines remain.
INFO:AFQ:Filtering by Cross Mid.
INFO:AFQ:After filtering by Cross Mid. (time: 0.0002377033233642578s), 7174 streamlines remain.
INFO:AFQ:Filtering by startpoint
INFO:AFQ:After filtering by startpoint (time: 0.6555018424987793s), 2541 streamlines remain.
INFO:AFQ:Filtering by endpoint
INFO:AFQ:After filtering by endpoint (time: 0.017009973526000977s), 243 streamlines remain.
INFO:AFQ:Filtering by include
INFO:AFQ:After filtering by include (time: 0.020737171173095703s), 103 streamlines remain.
INFO:AFQ:Filtering by exclude
INFO:AFQ:After filtering by exclude (time: 8.225440979003906e-05s), 103 streamlines remain.
INFO:AFQ:Filtering by Mahalanobis
INFO:AFQ:After filtering by Mahalanobis (time: 0.02273702621459961s), 38 streamlines remain.
INFO:AFQ:Finding Streamlines for CGC_L
INFO:AFQ:Filtering by Prob. Map
INFO:AFQ:After filtering by Prob. Map (time: 0.011155843734741211s), 5012 streamlines remain.
INFO:AFQ:Filtering by Cross Mid.
INFO:AFQ:After filtering by Cross Mid. (time: 9.799003601074219e-05s), 1584 streamlines remain.
INFO:AFQ:Filtering by startpoint
INFO:AFQ:After filtering by startpoint (time: 0.041005849838256836s), 561 streamlines remain.
INFO:AFQ:Filtering by include
INFO:AFQ:After filtering by include (time: 0.07077312469482422s), 121 streamlines remain.
INFO:AFQ:Filtering by exclude
INFO:AFQ:After filtering by exclude (time: 8.869171142578125e-05s), 121 streamlines remain.
INFO:AFQ:Filtering by Mahalanobis
INFO:AFQ:After filtering by Mahalanobis (time: 0.0237119197845459s), 24 streamlines remain.
INFO:AFQ:Finding Streamlines for CGC_R
INFO:AFQ:Filtering by Prob. Map
INFO:AFQ:After filtering by Prob. Map (time: 0.023638010025024414s), 6895 streamlines remain.
INFO:AFQ:Filtering by Cross Mid.
INFO:AFQ:After filtering by Cross Mid. (time: 0.00013589859008789062s), 3019 streamlines remain.
INFO:AFQ:Filtering by startpoint
INFO:AFQ:After filtering by startpoint (time: 0.0724799633026123s), 448 streamlines remain.
INFO:AFQ:Filtering by include
INFO:AFQ:After filtering by include (time: 0.07252311706542969s), 118 streamlines remain.
INFO:AFQ:Filtering by exclude
INFO:AFQ:After filtering by exclude (time: 9.584426879882812e-05s), 118 streamlines remain.
INFO:AFQ:Filtering by Mahalanobis
INFO:AFQ:After filtering by Mahalanobis (time: 0.022489070892333984s), 30 streamlines remain.
INFO:AFQ:Finding Streamlines for CST_L
INFO:AFQ:Filtering by Prob. Map
INFO:AFQ:After filtering by Prob. Map (time: 0.022454023361206055s), 6499 streamlines remain.
INFO:AFQ:Filtering by Cross Mid.
INFO:AFQ:After filtering by Cross Mid. (time: 0.0001327991485595703s), 4177 streamlines remain.
INFO:AFQ:Filtering by startpoint
INFO:AFQ:After filtering by startpoint (time: 0.10732889175415039s), 1462 streamlines remain.
INFO:AFQ:Filtering by endpoint
INFO:AFQ:After filtering by endpoint (time: 0.04527783393859863s), 585 streamlines remain.
INFO:AFQ:Filtering by include
INFO:AFQ:After filtering by include (time: 0.04770207405090332s), 207 streamlines remain.
INFO:AFQ:Filtering by exclude
INFO:AFQ:After filtering by exclude (time: 0.00012493133544921875s), 207 streamlines remain.
INFO:AFQ:Filtering by Mahalanobis
INFO:AFQ:After filtering by Mahalanobis (time: 0.03915715217590332s), 123 streamlines remain.
INFO:AFQ:Finding Streamlines for CST_R
INFO:AFQ:Filtering by Prob. Map
INFO:AFQ:After filtering by Prob. Map (time: 0.011193990707397461s), 5560 streamlines remain.
INFO:AFQ:Filtering by Cross Mid.
INFO:AFQ:After filtering by Cross Mid. (time: 0.00011706352233886719s), 3417 streamlines remain.
INFO:AFQ:Filtering by startpoint
INFO:AFQ:After filtering by startpoint (time: 0.08928394317626953s), 1365 streamlines remain.
INFO:AFQ:Filtering by endpoint
INFO:AFQ:After filtering by endpoint (time: 0.04257011413574219s), 546 streamlines remain.
INFO:AFQ:Filtering by include
INFO:AFQ:After filtering by include (time: 0.05051279067993164s), 263 streamlines remain.
INFO:AFQ:Filtering by exclude
INFO:AFQ:After filtering by exclude (time: 0.00016379356384277344s), 263 streamlines remain.
INFO:AFQ:Filtering by Mahalanobis
INFO:AFQ:After filtering by Mahalanobis (time: 0.03453683853149414s), 174 streamlines remain.
INFO:AFQ:Finding Streamlines for IFO_L
INFO:AFQ:Filtering by Prob. Map
INFO:AFQ:After filtering by Prob. Map (time: 0.011188983917236328s), 8628 streamlines remain.
INFO:AFQ:Filtering by Cross Mid.
INFO:AFQ:After filtering by Cross Mid. (time: 0.00015997886657714844s), 5412 streamlines remain.
INFO:AFQ:Filtering by startpoint
INFO:AFQ:After filtering by startpoint (time: 0.2286701202392578s), 1236 streamlines remain.
INFO:AFQ:Filtering by endpoint
INFO:AFQ:After filtering by endpoint (time: 0.038948774337768555s), 229 streamlines remain.
INFO:AFQ:Filtering by include
INFO:AFQ:After filtering by include (time: 0.13434600830078125s), 107 streamlines remain.
INFO:AFQ:Filtering by exclude
INFO:AFQ:After filtering by exclude (time: 9.393692016601562e-05s), 107 streamlines remain.
INFO:AFQ:Filtering by Mahalanobis
INFO:AFQ:After filtering by Mahalanobis (time: 0.022103071212768555s), 35 streamlines remain.
INFO:AFQ:Finding Streamlines for IFO_R
INFO:AFQ:Filtering by Prob. Map
INFO:AFQ:After filtering by Prob. Map (time: 0.011394977569580078s), 8358 streamlines remain.
INFO:AFQ:Filtering by Cross Mid.
INFO:AFQ:After filtering by Cross Mid. (time: 0.00016498565673828125s), 5154 streamlines remain.
INFO:AFQ:Filtering by startpoint
INFO:AFQ:After filtering by startpoint (time: 0.19711899757385254s), 1153 streamlines remain.
INFO:AFQ:Filtering by endpoint
INFO:AFQ:After filtering by endpoint (time: 0.033126115798950195s), 249 streamlines remain.
INFO:AFQ:Filtering by include
INFO:AFQ:After filtering by include (time: 0.14870405197143555s), 141 streamlines remain.
INFO:AFQ:Filtering by exclude
INFO:AFQ:After filtering by exclude (time: 9.393692016601562e-05s), 141 streamlines remain.
INFO:AFQ:Filtering by Mahalanobis
INFO:AFQ:After filtering by Mahalanobis (time: 0.02152085304260254s), 34 streamlines remain.
INFO:AFQ:Finding Streamlines for ILF_L
INFO:AFQ:Filtering by Prob. Map
INFO:AFQ:After filtering by Prob. Map (time: 0.011404037475585938s), 6807 streamlines remain.
INFO:AFQ:Filtering by Cross Mid.
INFO:AFQ:After filtering by Cross Mid. (time: 0.00012540817260742188s), 4797 streamlines remain.
INFO:AFQ:Filtering by startpoint
INFO:AFQ:After filtering by startpoint (time: 0.2034912109375s), 1247 streamlines remain.
INFO:AFQ:Filtering by endpoint
INFO:AFQ:After filtering by endpoint (time: 0.012362957000732422s), 145 streamlines remain.
INFO:AFQ:Filtering by include
INFO:AFQ:After filtering by include (time: 0.08051371574401855s), 92 streamlines remain.
INFO:AFQ:Filtering by exclude
INFO:AFQ:After filtering by exclude (time: 7.700920104980469e-05s), 92 streamlines remain.
INFO:AFQ:Filtering by Mahalanobis
INFO:AFQ:After filtering by Mahalanobis (time: 0.020299911499023438s), 20 streamlines remain.
INFO:AFQ:Finding Streamlines for ILF_R
INFO:AFQ:Filtering by Prob. Map
INFO:AFQ:After filtering by Prob. Map (time: 0.013399839401245117s), 6198 streamlines remain.
INFO:AFQ:Filtering by Cross Mid.
INFO:AFQ:After filtering by Cross Mid. (time: 0.00016498565673828125s), 4520 streamlines remain.
INFO:AFQ:Filtering by startpoint
INFO:AFQ:After filtering by startpoint (time: 0.17410683631896973s), 1128 streamlines remain.
INFO:AFQ:Filtering by endpoint
INFO:AFQ:After filtering by endpoint (time: 0.012157917022705078s), 104 streamlines remain.
INFO:AFQ:Filtering by include
INFO:AFQ:After filtering by include (time: 0.0627279281616211s), 34 streamlines remain.
INFO:AFQ:Filtering by exclude
INFO:AFQ:After filtering by exclude (time: 5.817413330078125e-05s), 34 streamlines remain.
INFO:AFQ:Filtering by Mahalanobis
INFO:AFQ:After filtering by Mahalanobis (time: 0.0005571842193603516s), 11 streamlines remain.
INFO:AFQ:Finding Streamlines for SLF_L
INFO:AFQ:Filtering by Prob. Map
INFO:AFQ:After filtering by Prob. Map (time: 0.014086246490478516s), 10677 streamlines remain.
INFO:AFQ:Filtering by Cross Mid.
INFO:AFQ:After filtering by Cross Mid. (time: 0.00019693374633789062s), 6295 streamlines remain.
INFO:AFQ:Filtering by startpoint
INFO:AFQ:After filtering by startpoint (time: 0.19895601272583008s), 1402 streamlines remain.
INFO:AFQ:Filtering by endpoint
INFO:AFQ:After filtering by endpoint (time: 0.01919412612915039s), 130 streamlines remain.
INFO:AFQ:Filtering by include
INFO:AFQ:After filtering by include (time: 0.05561685562133789s), 88 streamlines remain.
INFO:AFQ:Filtering by exclude
INFO:AFQ:After filtering by exclude (time: 0.006002902984619141s), 86 streamlines remain.
INFO:AFQ:Filtering by Mahalanobis
INFO:AFQ:After filtering by Mahalanobis (time: 0.021872282028198242s), 48 streamlines remain.
INFO:AFQ:Finding Streamlines for SLF_R
INFO:AFQ:Filtering by Prob. Map
INFO:AFQ:After filtering by Prob. Map (time: 0.011490106582641602s), 8473 streamlines remain.
INFO:AFQ:Filtering by Cross Mid.
INFO:AFQ:After filtering by Cross Mid. (time: 0.00015997886657714844s), 5408 streamlines remain.
INFO:AFQ:Filtering by startpoint
INFO:AFQ:After filtering by startpoint (time: 0.19147515296936035s), 1409 streamlines remain.
INFO:AFQ:Filtering by endpoint
INFO:AFQ:After filtering by endpoint (time: 0.019580841064453125s), 164 streamlines remain.
INFO:AFQ:Filtering by include
INFO:AFQ:After filtering by include (time: 0.08086085319519043s), 141 streamlines remain.
INFO:AFQ:Filtering by exclude
INFO:AFQ:After filtering by exclude (time: 0.00923919677734375s), 135 streamlines remain.
INFO:AFQ:Filtering by Mahalanobis
INFO:AFQ:After filtering by Mahalanobis (time: 0.02245187759399414s), 60 streamlines remain.
INFO:AFQ:Finding Streamlines for ARC_L
INFO:AFQ:Filtering by Prob. Map
INFO:AFQ:After filtering by Prob. Map (time: 0.013096094131469727s), 8727 streamlines remain.
INFO:AFQ:Filtering by Cross Mid.
INFO:AFQ:After filtering by Cross Mid. (time: 0.00015592575073242188s), 5836 streamlines remain.
INFO:AFQ:Filtering by startpoint
INFO:AFQ:After filtering by startpoint (time: 0.5174741744995117s), 2417 streamlines remain.
INFO:AFQ:Filtering by endpoint
INFO:AFQ:After filtering by endpoint (time: 0.060565948486328125s), 510 streamlines remain.
INFO:AFQ:Filtering by include
INFO:AFQ:After filtering by include (time: 0.14734387397766113s), 230 streamlines remain.
INFO:AFQ:Filtering by exclude
INFO:AFQ:After filtering by exclude (time: 0.00014901161193847656s), 230 streamlines remain.
INFO:AFQ:Filtering by Mahalanobis
INFO:AFQ:After filtering by Mahalanobis (time: 0.023514986038208008s), 41 streamlines remain.
INFO:AFQ:Finding Streamlines for ARC_R
INFO:AFQ:Filtering by Prob. Map
INFO:AFQ:After filtering by Prob. Map (time: 0.012474775314331055s), 7305 streamlines remain.
INFO:AFQ:Filtering by Cross Mid.
INFO:AFQ:After filtering by Cross Mid. (time: 0.00013375282287597656s), 5115 streamlines remain.
INFO:AFQ:Filtering by startpoint
INFO:AFQ:After filtering by startpoint (time: 0.4143991470336914s), 2079 streamlines remain.
INFO:AFQ:Filtering by endpoint
INFO:AFQ:After filtering by endpoint (time: 0.04330587387084961s), 599 streamlines remain.
INFO:AFQ:Filtering by include
INFO:AFQ:After filtering by include (time: 0.1697089672088623s), 288 streamlines remain.
INFO:AFQ:Filtering by exclude
INFO:AFQ:After filtering by exclude (time: 0.00016617774963378906s), 288 streamlines remain.
INFO:AFQ:Filtering by Mahalanobis
INFO:AFQ:After filtering by Mahalanobis (time: 0.015221118927001953s), 98 streamlines remain.
INFO:AFQ:Finding Streamlines for UNC_L
INFO:AFQ:Filtering by Prob. Map
INFO:AFQ:After filtering by Prob. Map (time: 0.017627954483032227s), 4523 streamlines remain.
INFO:AFQ:Filtering by Cross Mid.
INFO:AFQ:After filtering by Cross Mid. (time: 0.00010204315185546875s), 2718 streamlines remain.
INFO:AFQ:Filtering by startpoint
INFO:AFQ:After filtering by startpoint (time: 0.049046993255615234s), 496 streamlines remain.
INFO:AFQ:Filtering by endpoint
INFO:AFQ:After filtering by endpoint (time: 0.007899045944213867s), 125 streamlines remain.
INFO:AFQ:Filtering by include
INFO:AFQ:After filtering by include (time: 0.02147197723388672s), 64 streamlines remain.
INFO:AFQ:Filtering by exclude
INFO:AFQ:After filtering by exclude (time: 6.103515625e-05s), 64 streamlines remain.
INFO:AFQ:Filtering by Mahalanobis
INFO:AFQ:After filtering by Mahalanobis (time: 0.01752305030822754s), 22 streamlines remain.
INFO:AFQ:Finding Streamlines for UNC_R
INFO:AFQ:Filtering by Prob. Map
INFO:AFQ:After filtering by Prob. Map (time: 0.013573169708251953s), 3644 streamlines remain.
INFO:AFQ:Filtering by Cross Mid.
INFO:AFQ:After filtering by Cross Mid. (time: 8.893013000488281e-05s), 2141 streamlines remain.
INFO:AFQ:Filtering by startpoint
INFO:AFQ:After filtering by startpoint (time: 0.04164290428161621s), 499 streamlines remain.
INFO:AFQ:Filtering by endpoint
INFO:AFQ:After filtering by endpoint (time: 0.008275985717773438s), 123 streamlines remain.
INFO:AFQ:Filtering by include
INFO:AFQ:After filtering by include (time: 0.021188974380493164s), 68 streamlines remain.
INFO:AFQ:Filtering by exclude
INFO:AFQ:After filtering by exclude (time: 5.984306335449219e-05s), 68 streamlines remain.
INFO:AFQ:Filtering by Mahalanobis
INFO:AFQ:After filtering by Mahalanobis (time: 0.0236818790435791s), 33 streamlines remain.
INFO:AFQ:Finding Streamlines for FA
INFO:AFQ:Filtering by Prob. Map
INFO:AFQ:After filtering by Prob. Map (time: 0.01384592056274414s), 6804 streamlines remain.
INFO:AFQ:Filtering by Cross Mid.
INFO:AFQ:After filtering by Cross Mid. (time: 0.00012302398681640625s), 2403 streamlines remain.
INFO:AFQ:Filtering by startpoint
INFO:AFQ:After filtering by startpoint (time: 0.19993925094604492s), 1680 streamlines remain.
INFO:AFQ:Filtering by endpoint
INFO:AFQ:After filtering by endpoint (time: 0.07093596458435059s), 1157 streamlines remain.
INFO:AFQ:Filtering by include
INFO:AFQ:After filtering by include (time: 0.3254990577697754s), 356 streamlines remain.
INFO:AFQ:Filtering by exclude
INFO:AFQ:After filtering by exclude (time: 0.0001919269561767578s), 356 streamlines remain.
INFO:AFQ:Filtering by Mahalanobis
INFO:AFQ:After filtering by Mahalanobis (time: 0.025099992752075195s), 98 streamlines remain.
INFO:AFQ:Finding Streamlines for FP
INFO:AFQ:Filtering by Prob. Map
INFO:AFQ:After filtering by Prob. Map (time: 0.029061079025268555s), 5774 streamlines remain.
INFO:AFQ:Filtering by Cross Mid.
INFO:AFQ:After filtering by Cross Mid. (time: 0.00010704994201660156s), 2132 streamlines remain.
INFO:AFQ:Filtering by startpoint
INFO:AFQ:After filtering by startpoint (time: 0.08460783958435059s), 695 streamlines remain.
INFO:AFQ:Filtering by endpoint
INFO:AFQ:After filtering by endpoint (time: 0.02544116973876953s), 446 streamlines remain.
INFO:AFQ:Filtering by include
INFO:AFQ:After filtering by include (time: 0.17054414749145508s), 1 streamlines remain.
INFO:AFQ:Filtering by exclude
INFO:AFQ:After filtering by exclude (time: 5.2928924560546875e-05s), 1 streamlines remain.
INFO:AFQ:Filtering by Mahalanobis
INFO:AFQ:After filtering by Mahalanobis (time: 0.0001399517059326172s), 0 streamlines remain.
INFO:AFQ:Finding Streamlines for pARC_L
INFO:AFQ:Filtering by Cross Mid.
INFO:AFQ:After filtering by Cross Mid. (time: 0.0003707408905029297s), 13690 streamlines remain.
INFO:AFQ:Filtering by startpoint
INFO:AFQ:After filtering by startpoint (time: 0.3928399085998535s), 1067 streamlines remain.
INFO:AFQ:Filtering by orientation
INFO:AFQ:After filtering by orientation (time: 0.00773310661315918s), 366 streamlines remain.
INFO:AFQ:Filtering by include
INFO:AFQ:After filtering by include (time: 0.012845993041992188s), 97 streamlines remain.
INFO:AFQ:Filtering by exclude
INFO:AFQ:After filtering by exclude (time: 0.016633033752441406s), 97 streamlines remain.
INFO:AFQ:Filtering by Mahalanobis
INFO:AFQ:After filtering by Mahalanobis (time: 0.0002567768096923828s), 0 streamlines remain.
INFO:AFQ:Finding Streamlines for pARC_R
INFO:AFQ:Filtering by Cross Mid.
INFO:AFQ:After filtering by Cross Mid. (time: 0.0003600120544433594s), 13690 streamlines remain.
INFO:AFQ:Filtering by startpoint
INFO:AFQ:After filtering by startpoint (time: 0.4037799835205078s), 1044 streamlines remain.
INFO:AFQ:Filtering by orientation
INFO:AFQ:After filtering by orientation (time: 0.0074329376220703125s), 324 streamlines remain.
INFO:AFQ:Filtering by include
INFO:AFQ:After filtering by include (time: 0.015833139419555664s), 79 streamlines remain.
INFO:AFQ:Filtering by exclude
INFO:AFQ:After filtering by exclude (time: 0.012948989868164062s), 79 streamlines remain.
INFO:AFQ:Filtering by Mahalanobis
INFO:AFQ:After filtering by Mahalanobis (time: 0.00024700164794921875s), 0 streamlines remain.
INFO:AFQ:Finding Streamlines for VOF_L
INFO:AFQ:Filtering by Cross Mid.
INFO:AFQ:After filtering by Cross Mid. (time: 0.0003681182861328125s), 13690 streamlines remain.
INFO:AFQ:Filtering by startpoint
INFO:AFQ:After filtering by startpoint (time: 0.31522393226623535s), 819 streamlines remain.
INFO:AFQ:Filtering by endpoint
INFO:AFQ:After filtering by endpoint (time: 0.015855789184570312s), 263 streamlines remain.
INFO:AFQ:Filtering by orientation
INFO:AFQ:After filtering by orientation (time: 0.0018939971923828125s), 34 streamlines remain.
INFO:AFQ:Filtering by Mahalanobis
Traceback (most recent call last):
  File "/Users/arokem/source/pyAFQ/examples/tutorial_examples/plot_afq_api.py", line 185, in <module>
    bundle_html = myafq.export("all_bundles_figure")
  File "/Users/arokem/source/pyAFQ/AFQ/api/group.py", line 439, in export
    results[subject][session] = wf_dict[attr_name]
  File "/Users/arokem/miniconda3/envs/afq/lib/python3.10/site-packages/pimms/calculation.py", line 470, in __getitem__
    self._run_node(self.plan.efferents[k])
  File "/Users/arokem/miniconda3/envs/afq/lib/python3.10/site-packages/pimms/calculation.py", line 534, in _run_node
    if not found: res = node(self)
  File "/Users/arokem/miniconda3/envs/afq/lib/python3.10/site-packages/pimms/calculation.py", line 91, in __call__
    result = self.function(*args)
  File "/Users/arokem/source/pyAFQ/AFQ/tasks/viz.py", line 81, in viz_bundles
    profiles_file = segmentation_imap["profiles"]
  File "/Users/arokem/miniconda3/envs/afq/lib/python3.10/site-packages/pimms/calculation.py", line 470, in __getitem__
    self._run_node(self.plan.efferents[k])
  File "/Users/arokem/miniconda3/envs/afq/lib/python3.10/site-packages/pimms/calculation.py", line 534, in _run_node
    if not found: res = node(self)
  File "/Users/arokem/miniconda3/envs/afq/lib/python3.10/site-packages/pimms/calculation.py", line 90, in __call__
    args.append(opts[name])
  File "/Users/arokem/miniconda3/envs/afq/lib/python3.10/site-packages/pimms/util.py", line 856, in __getitem__
    return self._examine_val(k, ps.PMap.__getitem__(self, k))
  File "/Users/arokem/miniconda3/envs/afq/lib/python3.10/site-packages/pimms/util.py", line 852, in _examine_val
    val = val()
  File "/Users/arokem/miniconda3/envs/afq/lib/python3.10/site-packages/pimms/util.py", line 1131, in <lambda>
    def curry_choice(k, args): return lambda:choose_fn(k, args)
  File "/Users/arokem/miniconda3/envs/afq/lib/python3.10/site-packages/pimms/util.py", line 1100, in _choose_last
    return vs[-1][k]
  File "/Users/arokem/miniconda3/envs/afq/lib/python3.10/site-packages/pimms/calculation.py", line 470, in __getitem__
    self._run_node(self.plan.efferents[k])
  File "/Users/arokem/miniconda3/envs/afq/lib/python3.10/site-packages/pimms/calculation.py", line 534, in _run_node
    if not found: res = node(self)
  File "/Users/arokem/miniconda3/envs/afq/lib/python3.10/site-packages/pimms/calculation.py", line 91, in __call__
    result = self.function(*args)
  File "<string>", line 2, in wrapper_has_args_func
  File "/Users/arokem/source/pyAFQ/AFQ/tasks/decorators.py", line 147, in wrapper_as_file
    gen, meta = func(*args[:og_arg_count], **kwargs)
  File "/Users/arokem/source/pyAFQ/AFQ/tasks/segmentation.py", line 70, in segment
    bundles = segmentation.segment(
  File "/Users/arokem/source/pyAFQ/AFQ/segmentation.py", line 405, in segment
    fiber_groups = self.segment_afq()
  File "/Users/arokem/source/pyAFQ/AFQ/segmentation.py", line 789, in segment_afq
    b_sls.get_selected_sls(cut=cut),
  File "/Users/arokem/source/pyAFQ/AFQ/segmentation.py", line 92, in get_selected_sls
    self.roi_dists[idx, 0]:
AttributeError: '_SlsBeingRecognized' object has no attribute 'roi_dists'. Did you mean: 'n_roi_dists'?
```

I think that `roi_dists` should have already been set on [line 730](https://github.com/yeatmanlab/pyAFQ/blob/master/AFQ/segmentation.py#L730), but I am guessing that this line is not reached under some conditions. Still trying to understand what those conditions are, but thought I'd post here so we can keep track of this.

**Comment by 36000** [comment]
This may fix it: #1048
