### ISSUE TITLE
pyAFQ error

### ISSUE THREAD

**Issue by Qji12** [yeatmanlab/pyAFQ#172]
Hi All:
I just downloaded a new version pyAFQ and installed in my machine. I got following message when I trying to run on a test subject:

 Traceback (most recent call last):
  File "/work/qji/pyAFQ/bin/pyAFQ", line 89, in <module>
    myafq.export_bundles()
  File "/work/qji/miniconda3/lib/python3.6/site-packages/AFQ/api.py", line 1069, in export_bundles
    axis=1)
  File "/work/qji/miniconda3/lib/python3.6/site-packages/pandas/core/frame.py", line 6014, in apply
    return op.get_result()
  File "/work/qji/miniconda3/lib/python3.6/site-packages/pandas/core/apply.py", line 142, in get_result
    return self.apply_standard()
  File "/work/qji/miniconda3/lib/python3.6/site-packages/pandas/core/apply.py", line 248, in apply_standard
    self.apply_series_generator()
  File "/work/qji/miniconda3/lib/python3.6/site-packages/pandas/core/apply.py", line 277, in apply_series_generator
    results[i] = self.f(v)
  File "/work/qji/miniconda3/lib/python3.6/site-packages/pandas/core/apply.py", line 74, in f
    return func(x, *args, **kwds)
  File "/work/qji/miniconda3/lib/python3.6/site-packages/AFQ/api.py", line 575, in _export_bundles
    force_recompute=force_recompute)
  File "/work/qji/miniconda3/lib/python3.6/site-packages/AFQ/api.py", line 433, in _clean_bundles
    force_recompute=False)
  File "/work/qji/miniconda3/lib/python3.6/site-packages/AFQ/api.py", line 397, in _segment
    force_recompute=force_recompute)
  File "/work/qji/miniconda3/lib/python3.6/site-packages/AFQ/api.py", line 380, in _streamlines
    dwi_img.affine)
  File "/work/qji/miniconda3/lib/python3.6/site-packages/dipy/io/streamline.py", line 34, in save_tractogram
    _, extension = os.path.splitext(filename)
  File "/work/qji/miniconda3/lib/python3.6/posixpath.py", line 120, in splitext
    p = os.fspath(p)
TypeError: ('expected str, bytes or os.PathLike object, not generator', 'occurred at index 0')

This happen after tracking. I will appreciate if someone cna tell me what went wrong.

**Comment by arokem** [comment]
Thanks for reporting! This is indeed a bug. Should be fixed once #173 is merged.
