### ISSUE TITLE
default config file (from help text) is improper toml so cannot be used

### ISSUE THREAD

**Issue by gkiar** [yeatmanlab/pyAFQ#214]
When using something like `sphere = None` in `.toml`, the interpreter crashes because `None` is not a valid `toml` type. This means we cannot copy+paste the current version of the help-text suggested config file as is and have it run.

```
Traceback (most recent call last):
  File "/Users/greg/code/env/auto/bin/pyAFQ", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/Users/greg/code/gkiar/pyAFQ/bin/pyAFQ", line 108, in <module>
    config = toml.load(opts.config)
  File "/Users/greg/code/env/auto/lib/python3.7/site-packages/toml/decoder.py", line 112, in load
    return loads(ffile.read(), _dict, decoder)
  File "/Users/greg/code/env/auto/lib/python3.7/site-packages/toml/decoder.py", line 458, in loads
    raise TomlDecodeError(str(err), original, pos)
toml.decoder.TomlDecodeError: This float doesn't have a leading digit (line 19 column 1 char 378)
```

**Comment by arokem** [comment]
I believe this is closed through e6fb420
