### ISSUE TITLE
logging error on runtime

### ISSUE THREAD

**Issue by gkiar** [yeatmanlab/pyAFQ#215]
```
$ pyAFQ demo_pyafq.toml
--- Logging error ---
Traceback (most recent call last):
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1034, in emit
    msg = self.format(record)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 880, in format
    return fmt.format(record)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 619, in format
    record.message = record.getMessage()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 380, in getMessage
    msg = msg % self.args
TypeError: not all converted during string formatting
Call stack:
  File "/Users/greg/code/env/auto/bin/pyAFQ", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/Users/greg/code/gkiar/pyAFQ/bin/pyAFQ", line 103, in <module>
    "https://yeatmanlab.github.io/pyAFQ/usage.html#usage-tracking-with-google-analytics"  #noqa
Message: 'Your use of pyAFQ is being recorded using Google Analytics.'
Arguments: ('For more information, please refer to the pyAFQ documentation: ', 'https://yeatmanlab.github.io/pyAFQ/usage.html#usage-tracking-with-google-analyticsto turn this off, use the `--notrack` flag when using the pyAFQ CLI'
```

This can be resolved by removing some commas when the string is split across lines.

**Comment by arokem** [comment]
I believe this is closed through 7c5efdb
