### ISSUE TITLE
No streamlines selected for some ROIs, causing an error

### ISSUE THREAD

**Issue by gkiar** [yeatmanlab/pyAFQ#217]
Several ROIs seem to not find any streamlines for several ROIs(despite large numbers exceeding the probability threshold?), and in one cause this seems to cause a problem with list indexing/computing the length of an empty list.

```
NFO:AFQ.Segmentation:Assigning Streamlines to Bundles
INFO:AFQ.Segmentation:Finding Streamlines for ATR_R
INFO:AFQ.Segmentation:17600 streamlines exceed the probability threshold.
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 17600/17600 [00:11<00:00, 1577.63it/s]
INFO:AFQ.Segmentation:260 streamlines selected with waypoint ROIs
INFO:AFQ.Segmentation:Finding Streamlines for ATR_L
INFO:AFQ.Segmentation:21678 streamlines exceed the probability threshold.
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 21678/21678 [00:14<00:00, 1490.37it/s]
INFO:AFQ.Segmentation:919 streamlines selected with waypoint ROIs
INFO:AFQ.Segmentation:Finding Streamlines for CGC_R
INFO:AFQ.Segmentation:17426 streamlines exceed the probability threshold.
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 17426/17426 [00:05<00:00, 3263.36it/s]
INFO:AFQ.Segmentation:0 streamlines selected with waypoint ROIs
INFO:AFQ.Segmentation:Finding Streamlines for CGC_L
INFO:AFQ.Segmentation:15951 streamlines exceed the probability threshold.
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 15951/15951 [00:04<00:00, 3341.17it/s]
INFO:AFQ.Segmentation:0 streamlines selected with waypoint ROIs
INFO:AFQ.Segmentation:Finding Streamlines for CST_R
INFO:AFQ.Segmentation:9548 streamlines exceed the probability threshold.
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 9548/9548 [00:01<00:00, 8919.43it/s]
INFO:AFQ.Segmentation:0 streamlines selected with waypoint ROIs
INFO:AFQ.Segmentation:Finding Streamlines for CST_L
INFO:AFQ.Segmentation:10287 streamlines exceed the probability threshold.
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 10287/10287 [00:01<00:00, 7918.46it/s]
INFO:AFQ.Segmentation:0 streamlines selected with waypoint ROIs
INFO:AFQ.Segmentation:Finding Streamlines for HCC_R
INFO:AFQ.Segmentation:1540 streamlines exceed the probability threshold.
  0%|                                                                                                                                                    | 0/1540 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/Users/greg/code/env/auto/bin/pyAFQ", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/Users/greg/code/gkiar/pyAFQ/bin/pyAFQ", line 195, in <module>
    myafq.export_bundles()
  File "/Users/greg/code/gkiar/pyAFQ/AFQ/api.py", line 1187, in export_bundles
    axis=1)
  File "/Users/greg/code/env/auto/lib/python3.7/site-packages/pandas/core/frame.py", line 6014, in apply
    return op.get_result()
  File "/Users/greg/code/env/auto/lib/python3.7/site-packages/pandas/core/apply.py", line 142, in get_result
    return self.apply_standard()
  File "/Users/greg/code/env/auto/lib/python3.7/site-packages/pandas/core/apply.py", line 248, in apply_standard
    self.apply_series_generator()
  File "/Users/greg/code/env/auto/lib/python3.7/site-packages/pandas/core/apply.py", line 277, in apply_series_generator
    results[i] = self.f(v)
  File "/Users/greg/code/env/auto/lib/python3.7/site-packages/pandas/core/apply.py", line 74, in f
    return func(x, *args, **kwds)
  File "/Users/greg/code/gkiar/pyAFQ/AFQ/api.py", line 671, in _export_bundles
    clean_params)
  File "/Users/greg/code/gkiar/pyAFQ/AFQ/api.py", line 485, in _clean_bundles
    clean_params)
  File "/Users/greg/code/gkiar/pyAFQ/AFQ/api.py", line 449, in _segment
    reg_prealign=reg_prealign)
  File "/Users/greg/code/gkiar/pyAFQ/AFQ/segmentation.py", line 229, in segment
    return self.segment_afq()
  File "/Users/greg/code/gkiar/pyAFQ/AFQ/segmentation.py", line 458, in segment_afq
    tol)
  File "/Users/greg/code/gkiar/pyAFQ/AFQ/segmentation.py", line 369, in _check_sl_with_inclusion
    if np.min(dist[-1]) > tol:
  File "/Users/greg/code/env/auto/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 2442, in amin
    initial=initial)
  File "/Users/greg/code/env/auto/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 83, in _wrapreduction
    return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
ValueError: ('zero-size array to reduction operation minimum which has no identity', 'occurred at index 0')
```

**Comment by arokem** [comment]
I think that this will be much easier to handle once we have an OO interface for bundles, currently developing in #176

**Comment by arokem** [comment]
Sorry - meant to point to #184

**Comment by 36000** [comment]
Moved to #397
