### ISSUE TITLE
error for run pyAFQ on qsiprep-preprocessed data

### ISSUE THREAD

**Issue by weiwei-wch** [yeatmanlab/pyAFQ#263]
Hi all！
    recently I run pyAFQ on some qsiprep-preprocessed data and followed error occured. before this error I ran pyAFQ on data only preprocessed by eddy successfully. is there any way to solve this problem?
Here is the error code:
INFO:AFQ.tractography:Tracking...
100%
INFO:AFQ.api:Saving /home/weiwei/Desktop/AFQtest/afq/sub-N5110WWEIWEI/sess01/sub-N5110WWEIWEI_sess-01_dwi_space-RASMM_model-DTI_desc-det_tractography.trk
Traceback (most recent call last):
  File "/usr/local/bin/pyAFQ", line 198, in <module>
    myafq.export_ROI_gifs()
  File "/usr/local/lib/python3.6/dist-packages/AFQ/api.py", line 1360, in export_ROI_gifs
    self.data_frame.apply(self._export_ROI_gifs, axis=1)
  File "/usr/local/lib/python3.6/dist-packages/pandas/core/frame.py", line 6014, in apply
    return op.get_result()
  File "/usr/local/lib/python3.6/dist-packages/pandas/core/apply.py", line 142, in get_result
    return self.apply_standard()
  File "/usr/local/lib/python3.6/dist-packages/pandas/core/apply.py", line 248, in apply_standard
    self.apply_series_generator()
  File "/usr/local/lib/python3.6/dist-packages/pandas/core/apply.py", line 277, in apply_series_generator
    results[i] = self.f(v)
  File "/usr/local/lib/python3.6/dist-packages/AFQ/api.py", line 1055, in _export_ROI_gifs
    bundles_file = self._clean_bundles(row)
  File "/usr/local/lib/python3.6/dist-packages/AFQ/api.py", line 817, in _clean_bundles
    bundles_file = self._segment(row)
  File "/usr/local/lib/python3.6/dist-packages/AFQ/api.py", line 774, in _segment
    tg = load_tractogram(streamlines_file, img, Space.VOX)
  File "/usr/local/lib/python3.6/dist-packages/dipy/io/streamline.py", line 135, in load_tractogram
    if not is_header_compatible(filename, reference):
  File "/usr/local/lib/python3.6/dist-packages/dipy/io/utils.py", line 321, in is_header_compatible
    reference_2)
  File "/usr/local/lib/python3.6/dist-packages/dipy/io/utils.py", line 278, in get_reference_info
    raise ValueError('Invalid affine, contains only zeros.'
ValueError: ('Invalid affine, contains only zeros.Cannot determine voxel order from transformation', 'occurred at index 0')

**Comment by arokem** [comment]
I am not sure what this is about -- but would be happy to investigate further. Why did you close the issue? Did you manage to somehow solve this on your own?

**Comment by arokem** [comment]
If this is still an issue, is there any chance you could share the file `'sub-N5110WWEIWEI_sess-01_dwi_space-RASMM_model-DTI_desc-det_tractography.trk'`? Seems like there is some problem with this file.

**Comment by weiwei-wch** [comment]
yeah thanks for your attentsion. I finally figured out this problem was caused by the zeroed-out sform of header of preprocessed output dwi file of qsiprep, whcih is as a consequense of use of ANTs. It is easy to solve this by simply copy the qform to the sform of the dwi file, with some codes like this:

import nibabel as nb
img = nb.load('dwi/output/of/qsiprep')
qform = img.header.get_qform()
img.header.set_sform(qform,1)
img.to_filename('filename/of/output')

then the qsiprep-preprocessed dwi file can be used in AFQ

**Comment by arokem** [comment]
Awesome. Thanks for reporting back here! This information will surely save
others time.

Let me keep this open until we find a place to document this more
permanently.

**Comment by 36000** [comment]
This is solved in dipy 1.2.0, which we just merged!
