### ISSUE TITLE
API should provide more meaningful errors to users when can't find BIDS files

### ISSUE THREAD

**Issue by bloomdt-uw** [yeatmanlab/pyAFQ#554]
Currently generate `IndexError`

```
Traceback (most recent call last):
  File "/visual_pathways_api.py", line 159, in <module>
    myafq = api.AFQ(
  File "/pyAFQ/AFQ/api.py", line 545, in __init__
    bids_layout.get(subject=subject, session=session,
IndexError: list index out of range
```

https://github.com/yeatmanlab/pyAFQ/blob/c826d64c29cf0c6f701023e752ee53600358dfb7/AFQ/api.py#L524-L563

**Comment by bloomdt-uw** [comment]
Related #303
